### ISSUE TITLE
I cannot change Left Navigation 

### ISSUE THREAD

**Issue by nazrdogan** [appcelerator-se/corporate-directory#19]
How can change left navigation icon (**Appcelerator icon)**  ?

![simulator screen shot 02 may 2016 20 24 50](https://cloud.githubusercontent.com/assets/1672303/14963386/0fc94ac4-10ac-11e6-9c83-d086f2e063a9.png)

I find this directory.tss but its never used

```
".logo":{
    text: "\ue601",     // Unicode for Appcelerator Logo icon font
    color: "#C41230",
    font:{
        fontFamily:"icomoon",
        fontSize:36
    }
},
```

**Comment by grantges** [comment]
that logo reference is old, i'll need to remove it.

You can see where we add the left nav button here

https://github.com/appcelerator-se/corporate-directory/blob/master/app/controllers/directory.js#L197

You can replace the icon with a label or image.
