### ISSUE TITLE
Android error..."Get Google Play Services"

### ISSUE THREAD

**Issue by safadig** [appcelerator-se/corporate-directory#21]
Great App and instructions..Thank you
I am running on error trying to open detail view on Android Emulator and devices. The Emulator shows "Get Google Play Services" and when clicked crashes. On Device crashes on opening detailed view.

Works Perfect on iOS...
Any help is greatly appreciated. Thanks

**Comment by mauropm** [comment]
@safadig  hello! you need to use a emulator that includes the google maps and services. Check this small tutorial: http://hmkcode.com/run-google-map-v2-on-android-emulator/

**Comment by safadig** [comment]
Great. Thanks
