### ISSUE TITLE
Contact Information 

### ISSUE THREAD

**Issue by svora** [appcelerator-se/corporate-directory#3]
Per this URL, https://github.com/appcelerator-se/corporate-directory/blob/master/screenshots/app-navigation-animated.gif?raw=true . the app navigation, DetailView => Profile View => View “Contact Information” shows the  Maps with geo-location in the video. However, it does not for me on my my emulator or simulator. Could you please confirm the expected behavior?

**Comment by grantges** [comment]
@svora  - Thanks for filing this! This screenshot/animation should be updated with the latest UI changes. I'll get that updated here so as not to cause confusion.
