### ISSUE TITLE
Implement proper search mechanism on Android

### ISSUE THREAD

**Issue by ricardoalcocer** [appcelerator-se/corporate-directory#4]
Dependent on this ticket: https://jira.appcelerator.org/browse/TIMOB-16838

The ActionBar Search view is THE way of performing list searches on Android.  The way it is right now, shows the keyboard as soon as the app loads:

![](http://sht.tl/ELqBnj)

**Comment by grantges** [comment]
Now leveraging the SearchView in the ActionBar for this feature. :+1: 

![screen shot 2015-06-25 at 2 51 22 pm](https://cloud.githubusercontent.com/assets/16177/8364978/b97d1350-1b4f-11e5-9ae7-d0ec310da09f.png)
