### ISSUE TITLE
Android bookmark icon

### ISSUE THREAD

**Issue by ricardoalcocer** [appcelerator-se/corporate-directory#6]
The Bookmark/favorite icon on Android is the star (ic_menu_star) http://androiddrawables.com/Menu.html.  The app is currently using the one for iOS, which makes no sense to Android users.

**Comment by grantges** [comment]
will review and update for Android in an upcoming release.

**Comment by grantges** [comment]
I've updated the app to leverage the star icon for favorites for both iOS and Android

![screen shot 2015-06-25 at 3 03 22 pm](https://cloud.githubusercontent.com/assets/16177/8364960/986f0d58-1b4f-11e5-8ad5-9bbdc8a20c28.png)
