### ISSUE TITLE
Profile screen horizontal pages

### ISSUE THREAD

**Issue by ricardoalcocer** [appcelerator-se/corporate-directory#7]
There's no indication of that bottom area being multi-page.  A good idea could be to add dots in the bottom representing the amount of additional pages.  Here's how Google Fit does this (look on the left, in the circular progress bar.  There are two available pages): ![](http://bit.ly/1s0Mgj1)

**Comment by jrhinehart** [comment]
Hey guys,
      I should probably be removed from this channel, not being with the
company any more and all :) Hope all is well,

--Josh

**Comment by grantges** [comment]
We've addressed this with a more straight forward UI. closing.

@jrhinehart - No problem its open source :)
